"""
Takes data considered indexs as input and creates a csv considering only those files, and target values are renamed starting from 0 to ...
"""

import numpy as np
import os
dataset_considered = [91, 51, 89, 76]
dataset_considered = [6, 4,101,91]
no_of_rows = 60
# sunfloer, helicopter, stop_sign, revolver
true_labels = {0: 'BACKGROUND_Google',
               1: 'Faces',
               2: 'Faces_easy',
               3: 'Leopards',
               4: 'Motorbikes',
               5: 'accordion',
               6: 'airplanes',
               7: 'anchor',
               8: 'ant',
               9: 'barrel',
               10: 'bass',
               11: 'beaver',
               12: 'binocular',
               13: 'bonsai',
               14: 'brain',
               15: 'brontosaurus',
               16: 'buddha',
               17: 'butterfly',
               18: 'camera',
               19: 'cannon',
               20: 'car_side',
               21: 'ceiling_fan',
               22: 'cellphone',
               23: 'chair',
               24: 'chandelier',
               25: 'cougar_body',
               26: 'cougar_face',
               27: 'crab',
               28: 'crayfish',
               29: 'crocodile',
               30: 'crocodile_head',
               31: 'cup',
               32: 'dalmatian',
               33: 'dollar_bill',
               34: 'dolphin',
               35: 'dragonfly',
               36: 'electric_guitar',
               37: 'elephant',
               38: 'emu',
               39: 'euphonium',
               40: 'ewer',
               41: 'ferry',
               42: 'flamingo',
               43: 'flamingo_head',
               44: 'garfield',
               45: 'gerenuk',
               46: 'gramophone',
               47: 'grand_piano',
               48: 'hawksbill',
               49: 'headphone',
               50: 'hedgehog',
               51: 'helicopter',
               52: 'ibis',
               53: 'inline_skate',
               54: 'joshua_tree',
               55: 'kangaroo',
               56: 'ketch',
               57: 'lamp',
               58: 'laptop',
               59: 'llama',
               60: 'lobster',
               61: 'lotus',
               62: 'mandolin',
               63: 'mayfly',
               64: 'menorah',
               65: 'metronome',
               66: 'minaret',
               67: 'nautilus',
               68: 'octopus',
               69: 'okapi',
               70: 'pagoda',
               71: 'panda',
               72: 'pigeon',
               73: 'pizza',
               74: 'platypus',
               75: 'pyramid',
               76: 'revolver',
               77: 'rhino',
               78: 'rooster',
               79: 'saxophone',
               80: 'schooner',
               81: 'scissors',
               82: 'scorpion',
               83: 'sea_horse',
               84: 'snoopy',
               85: 'soccer_ball',
               86: 'stapler',
               87: 'starfish',
               88: 'stegosaurus',
               89: 'stop_sign',
               90: 'strawberry',
               91: 'sunflower',
               92: 'tick',
               93: 'trilobite',
               94: 'umbrella',
               95: 'watch',
               96: 'water_lilly',
               97: 'wheelchair',
               98: 'wild_cat',
               99: 'windsor_chair',
               100: 'wrench',
               101: 'yin_yang'}
data_len = [468,
            435,
            435,
            200,
            798,
            55,
            800,
            42,
            42,
            47,
            54,
            46,
            33,
            128,
            98,
            43,
            85,
            91,
            50,
            43,
            123,
            47,
            59,
            62,
            107,
            47,
            69,
            73,
            70,
            50,
            51,
            57,
            67,
            52,
            65,
            68,
            75,
            64,
            53,
            64,
            85,
            67,
            67,
            45,
            34,
            34,
            51,
            99,
            100,
            42,
            54,
            88,
            80,
            31,
            64,
            86,
            114,
            61,
            81,
            78,
            41,
            66,
            43,
            40,
            87,
            32,
            76,
            55,
            35,
            39,
            47,
            38,
            45,
            53,
            34,
            57,
            82,
            59,
            49,
            40,
            63,
            39,
            84,
            57,
            35,
            64,
            45,
            86,
            59,
            64,
            35,
            85,
            49,
            86,
            75,
            239,
            37,
            59,
            34,
            56,
            39,
            60]
import pandas
base_path = "/home/k_mathin/PycharmProjects/DataMiningClass/datasets/classification/object_classification/with_targets/"
output_path = "/home/k_mathin/PycharmProjects/DataMiningClass/datasets/classification/object_classification/yin_airpl_m_sun/"
files_list = os.listdir(base_path)

for files in files_list:
    df = pandas.read_csv(
        base_path + files
    )

    x = df.values
    temp = []
    count = 0
    for i in dataset_considered:
        index_value = sum(data_len[0:i])
        # table_value = x[index_value:index_value + data_len[i]]
        table_value = x[index_value:index_value + no_of_rows] # to have equal feature distribution
        table_value[:, df.shape[-1]-1] = count
        temp.append(table_value)
        count += 1
    y = np.concatenate(temp, axis=0)
    df1 = pandas.DataFrame(y)
    out_name = 'target_'
    for j in dataset_considered:
        out_name = out_name + str(j) + "_"
    df1.to_csv(output_path+out_name+files)
